### ISSUE TITLE
Lack of comments in the code

### ISSUE THREAD

**Issue by btmatthew** [btmatthew/Ai#1]
This will make the learning process easier for students, if someone who like to comment out the code, I would greatly appreciate it.

**Comment by Flawless2020** [comment]
Hi Matthew, I would like to help commenting out the code so users can understand the code and the logic behind it easier.

**Comment by btmatthew** [comment]
Dear @Flawless2020,

That would be great, I will assign this work to you very soon.

Matthew

**Comment by Flawless2020** [comment]
Please look at the commented version of the code that I've already pushed onto my branch. If you are happy with the code please merge it together. Thank you.

**Comment by btmatthew** [comment]
Brilliant start working on the code and I will merge it with master version.

Kind regards,

Matthew Bulat

**Comment by btmatthew** [comment]
I have merged your fork to the main version, #2

**Comment by Flawless2020** [comment]
Dear Matthew, I have made a few improvements to the original program in the sense that the users can choose if they want to display only one path between the two nodes on the screen or all the possible paths. The system is also modified to use System.nanoTime(); in order to measure the time taken to execute the program. This will significantly enhances the quality of the code as it supposed to be. Please check to see if you are happy with the changes to be merged into the project. Thank you very much for your time and cooperation.

**Comment by btmatthew** [comment]
Brilliant I have merge your code into the main branch #3

**Comment by Flawless2020** [comment]
Dear Matthew, I have tested the system against a few examples of larger scale of data and found out that the current system' performances is not satisfactory. I am looking to develop a new system for solving mazes that perform much faster and specifically should work with almost any size of maze files. I will upload the code once it's completed. The new system however should provide learners with a better view of Artificial intelligence approach to solve any kind of given maze files. Thanks for your time and collaboration.

**Comment by btmatthew** [comment]
Great! Please do that, once you are done with the code, let me know and I will test it and merge it to the main branch.

Thank

**Comment by Flawless2020** [comment]
Dear Matthew, I have created a new version of the Maze solver class which consistently enhances functionality and boosts user experience. I have tested the code and could not identify any issues. Can you please have a look at the new version of MazeSolver class for any issues or else we can merge the code into the main branch if you are happy with the new version. Thank you very much in advance for your time and cooperation.

**Comment by btmatthew** [comment]
Hey @Flawless2020 Thank you for your contribution, I really appreciate. I have tested your code, and it is running great, amazing job.

I had little problem merging the forks together. Therefore I have manualy copied the file over to my fork.

Once again great job, and thanks alot for your work.
